// Package storage provides interfaces for incident state persistence.
package storage

import (
	"context"
	"time"

	"github.com/rbias/nightcrier/internal/events"
	"github.com/rbias/nightcrier/internal/incident"
)

// StateStore defines the interface for persisting incident state to a SQL database.
// This interface supports the full incident lifecycle from creation through resolution.
// All methods are context-aware to support cancellation and timeouts.
type StateStore interface {
	// CreateIncident creates a new incident from a fault event.
	// This is called when a fault event is received and converted to an incident.
	// Returns the created incident with populated ID and timestamps.
	CreateIncident(ctx context.Context, inc *incident.Incident, event *events.FaultEvent) error

	// UpdateIncidentStatus updates the status of an existing incident.
	// This is called during state transitions (pending -> investigating, investigating -> resolved, etc.).
	// The startedAt timestamp is set when transitioning to investigating status.
	UpdateIncidentStatus(ctx context.Context, incidentID string, status string, startedAt *time.Time) error

	// CompleteIncident marks an incident as complete with final result information.
	// This is called when the agent finishes execution (success or failure).
	// Records the exit code, completion time, and any failure reason.
	CompleteIncident(ctx context.Context, incidentID string, exitCode int, failureReason string) error

	// RecordAgentExecution records details of an agent execution attempt.
	// This is called when starting and completing agent execution.
	// Links the execution to its parent incident.
	RecordAgentExecution(ctx context.Context, exec *AgentExecution) error

	// RecordTriageReport stores the investigation report generated by the agent.
	// This is called after the agent produces investigation.md output.
	// The report content is stored in markdown format.
	RecordTriageReport(ctx context.Context, report *TriageReport) error

	// GetIncident retrieves an incident by its ID (optional for initial implementation).
	// This supports future query and dashboard features.
	GetIncident(ctx context.Context, incidentID string) (*incident.Incident, error)

	// ListIncidents returns incidents matching the provided filters (optional for initial implementation).
	// This supports future query and dashboard features.
	ListIncidents(ctx context.Context, filters *IncidentFilters) ([]*incident.Incident, error)

	// Close releases any resources held by the StateStore.
	// Should be called during application shutdown.
	Close() error
}

// AgentExecution represents a single agent execution attempt for an incident.
type AgentExecution struct {
	// ExecutionID is the unique identifier for this execution attempt
	ExecutionID string
	// IncidentID links this execution to its parent incident
	IncidentID string
	// StartedAt is when the agent execution began
	StartedAt time.Time
	// CompletedAt is when the agent execution finished (nil if still running)
	CompletedAt *time.Time
	// ExitCode is the agent process exit code (nil if still running)
	ExitCode *int
	// ErrorMessage contains any error that occurred during execution
	ErrorMessage string
	// LogPaths contains filesystem paths to log files
	LogPaths map[string]string
}

// TriageReport represents the investigation report generated by the agent.
type TriageReport struct {
	// ReportID is the unique identifier for this report
	ReportID string
	// IncidentID links this report to its parent incident
	IncidentID string
	// ExecutionID links this report to the agent execution that generated it
	ExecutionID string
	// GeneratedAt is when the report was created
	GeneratedAt time.Time
	// ReportMarkdown is the full investigation report in markdown format
	ReportMarkdown string
	// ReportHTML is the HTML-rendered version of the report (optional)
	ReportHTML string
}

// IncidentFilters defines filters for querying incidents.
type IncidentFilters struct {
	// Status filters by incident status (pending, investigating, resolved, failed)
	Status []string
	// Cluster filters by cluster name
	Cluster string
	// Namespace filters by Kubernetes namespace
	Namespace string
	// FaultType filters by fault type
	FaultType string
	// Severity filters by severity level
	Severity string
	// CreatedAfter filters incidents created after this time
	CreatedAfter *time.Time
	// CreatedBefore filters incidents created before this time
	CreatedBefore *time.Time
	// Limit limits the number of results returned
	Limit int
	// Offset specifies the starting position for pagination
	Offset int
}
