-- Initial schema for nightcrier state persistence
-- Compatible with both SQLite and PostgreSQL

-- fault_events table stores the raw fault events received from kubernetes-mcp-server
CREATE TABLE IF NOT EXISTS fault_events (
    -- Primary key
    fault_id TEXT PRIMARY KEY,

    -- Event metadata
    subscription_id TEXT NOT NULL,
    cluster TEXT NOT NULL,
    received_at TIMESTAMP NOT NULL,

    -- Resource information
    resource_api_version TEXT,
    resource_kind TEXT,
    resource_name TEXT,
    resource_namespace TEXT,
    resource_uid TEXT,

    -- Fault details
    fault_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    context TEXT NOT NULL,
    timestamp TEXT NOT NULL,

    -- Indexes for common queries
    CONSTRAINT idx_fault_events_cluster CHECK (cluster <> ''),
    CONSTRAINT idx_fault_events_fault_type CHECK (fault_type <> '')
);

CREATE INDEX IF NOT EXISTS idx_fault_events_cluster ON fault_events(cluster);
CREATE INDEX IF NOT EXISTS idx_fault_events_received_at ON fault_events(received_at);
CREATE INDEX IF NOT EXISTS idx_fault_events_fault_type ON fault_events(fault_type);
CREATE INDEX IF NOT EXISTS idx_fault_events_severity ON fault_events(severity);

-- incidents table stores the investigation incidents created from fault events
CREATE TABLE IF NOT EXISTS incidents (
    -- Primary key
    incident_id TEXT PRIMARY KEY,

    -- Links to fault event
    fault_id TEXT NOT NULL,
    triggering_event_id TEXT,

    -- Lifecycle timestamps
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,

    -- Result information
    exit_code INTEGER,
    failure_reason TEXT,

    -- Context from event (denormalized for query performance)
    cluster TEXT NOT NULL,
    namespace TEXT,
    fault_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    context TEXT NOT NULL,
    timestamp TEXT NOT NULL,

    -- Resource information (denormalized)
    resource_api_version TEXT,
    resource_kind TEXT,
    resource_name TEXT,
    resource_namespace TEXT,
    resource_uid TEXT,

    -- Foreign key
    FOREIGN KEY (fault_id) REFERENCES fault_events(fault_id),

    -- Constraints
    CONSTRAINT chk_incidents_status CHECK (status IN ('pending', 'investigating', 'resolved', 'failed', 'agent_failed')),
    CONSTRAINT chk_incidents_cluster CHECK (cluster <> ''),
    CONSTRAINT chk_incidents_fault_type CHECK (fault_type <> '')
);

CREATE INDEX IF NOT EXISTS idx_incidents_fault_id ON incidents(fault_id);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_cluster ON incidents(cluster);
CREATE INDEX IF NOT EXISTS idx_incidents_created_at ON incidents(created_at);
CREATE INDEX IF NOT EXISTS idx_incidents_namespace ON incidents(namespace);
CREATE INDEX IF NOT EXISTS idx_incidents_fault_type ON incidents(fault_type);
CREATE INDEX IF NOT EXISTS idx_incidents_severity ON incidents(severity);

-- agent_executions table stores details of agent execution attempts
CREATE TABLE IF NOT EXISTS agent_executions (
    -- Primary key
    execution_id TEXT PRIMARY KEY,

    -- Links to incident
    incident_id TEXT NOT NULL,

    -- Execution lifecycle
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    exit_code INTEGER,
    error_message TEXT,

    -- Log file paths (stored as JSON for flexibility)
    -- Example: {"stdout": "/path/to/stdout.log", "stderr": "/path/to/stderr.log"}
    log_paths TEXT,

    -- Foreign key
    FOREIGN KEY (incident_id) REFERENCES incidents(incident_id),

    -- Constraints
    CONSTRAINT chk_agent_executions_incident_id CHECK (incident_id <> '')
);

CREATE INDEX IF NOT EXISTS idx_agent_executions_incident_id ON agent_executions(incident_id);
CREATE INDEX IF NOT EXISTS idx_agent_executions_started_at ON agent_executions(started_at);

-- triage_reports table stores the investigation reports generated by agents
CREATE TABLE IF NOT EXISTS triage_reports (
    -- Primary key
    report_id TEXT PRIMARY KEY,

    -- Links to incident and execution
    incident_id TEXT NOT NULL,
    execution_id TEXT NOT NULL,

    -- Report metadata
    generated_at TIMESTAMP NOT NULL,

    -- Report content (markdown and optional HTML)
    report_markdown TEXT NOT NULL,
    report_html TEXT,

    -- Foreign keys
    FOREIGN KEY (incident_id) REFERENCES incidents(incident_id),
    FOREIGN KEY (execution_id) REFERENCES agent_executions(execution_id),

    -- Constraints
    CONSTRAINT chk_triage_reports_incident_id CHECK (incident_id <> ''),
    CONSTRAINT chk_triage_reports_execution_id CHECK (execution_id <> '')
);

CREATE INDEX IF NOT EXISTS idx_triage_reports_incident_id ON triage_reports(incident_id);
CREATE INDEX IF NOT EXISTS idx_triage_reports_execution_id ON triage_reports(execution_id);
CREATE INDEX IF NOT EXISTS idx_triage_reports_generated_at ON triage_reports(generated_at);
